### ISSUE TITLE
[Request] Unit/Template Tests for helm chart

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-helm#142]
## Describe the feature

> Not related to this PR but one suggestion I think we might benefit from is unit/template testing for helm chart. This can help: https://github.com/helm-unittest/helm-unittest

> During this PR, it took me a while to see that the `---` (yaml separator) leaked into a template field (e.g. `namespace: myns---`) due to space trimming but chart renders fine. It would be nice to have testing to ease debugging :D

_Originally posted by @tthvo in https://github.com/cryostatio/cryostat-helm/issues/128#issuecomment-2136249999_

## Anything other information?

Down the line, we can establish some more e2e tests like scorecards, on top of the connection test: https://helm.sh/docs/topics/chart_tests/

**Comment by tthvo** [comment]
This requires a bit of research to design a framework and conventions. @ebaron @andrewazores what are your thoughts?

**Comment by andrewazores** [comment]
It's worth investing the time into. After 3.0 is shipped we should continue to spend some time on improving the overall testing situation because 3.0 is quite far behind what 2.4 had, which already didn't have as much automated testing as I would like.

Adding more testing capabilities at higher levels of abstraction, like the Helm chart and Operator scorecard tests, seems like a powerful tool. Something we have always lacked in our automated testing has been the capability to test with different configuration parameters (ie environment variables), so that was only ever done in the old codebase by whitebox unit testing and using mocks to test very specific behaviours under different environment variable settings. Testing at these higher levels lets us do integration/end-to-end testing under those conditions which is very preferable.

**Comment by tthvo** [comment]
Thanks, sounds good! @mwangggg @aali309 anyone interested in this work?

**Comment by aali309** [comment]
> Thanks, sounds good! @mwangggg @aali309 anyone interested in this work?

Yes, I can try to look at it and see how far I can go once done with my pending PRs.

**Comment by tthvo** [comment]
I guess this can now be closed?
